luafile $HOME/.config/nvim/lua/plugins.lua
luafile $HOME/.config/nvim/lua/config/nvim-global.lua
luafile $HOME/.config/nvim/lua/config/nvim-tree.lua
luafile $HOME/.config/nvim/lua/config/barbar.lua
luafile $HOME/.config/nvim/lua/config/null-ls.lua
luafile $HOME/.config/nvim/lua/config/git-signs.lua
luafile $HOME/.config/nvim/lua/config/snippets.lua
luafile $HOME/.config/nvim/lua/config/tree-sitter.lua
luafile $HOME/.config/nvim/lua/lsp/init.lua
luafile $HOME/.config/nvim/lua/keymaps.lua
