require("config.nvim-global")
require("config.barbar")
require("config.git-signs")
require("config.null-ls")
require("config.nvim-tree")
require("config.snippets")
require("config.statusline")
require("config.tree-sitter")
